title: OdenseNLP
description: Natural Language Processing Research Group at the University of Southern Denmark (SDU)
url: ""
baseurl: ""
timezone: Europe/Copenhagen
permalink: pretty
markdown: kramdown

collections:
  members:
    output: true
    permalink: /members/:name/
  thesis_projects:
    output: true
    permalink: /students/thesis-projects/:slug/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      category: news
      image: /assets/images/news/news-placeholder.svg
  - scope:
      path: ""
      type: members
    values:
      layout: member
      image: /assets/images/members/member-placeholder.svg
  - scope:
      path: ""
      type: thesis_projects
    values:
      layout: thesis-project
